### ISSUE TITLE
Add code formatting

### ISSUE THREAD

**Issue by vil1** [scalaz/scalaz-sbt#4]
The plugin should add support for scalafmt and configure it to run at least upon each compilation. 

We might also want to configure PR builds to make sure code is properly formatted.

**Comment by josipgrgurica** [comment]
I'll take this one.
Do we want to have the same scalafmt config file for all projects?

**Comment by vil1** [comment]
Sorry I missed your question. Yes, I think we definitely want to have a uniform style across all projects. 
Is it possible to define the configuration at the plugin level, or should we impose a standard `.scalafmt.conf` in [the template](https://github.com/scalaz/scalaz-library.g8)?

**Comment by josipgrgurica** [comment]
It is possible to define it at the plugin level. I don't know what is better approach, plugin or template, for that.

**Comment by vil1** [comment]
I think providing the conf from the plugin is the better approach (the template is used only once at the project creation)

**Comment by josipgrgurica** [comment]
Ok, what should be content of config file?
Do we want it to be the same as in [scalaz-zio](https://github.com/scalaz/scalaz-zio/blob/master/.scalafmt.conf)?

**Comment by vil1** [comment]
The one in [scalaz-yaml](https://github.com/scalaz/scalaz-yaml/blob/master/.scalafmt.conf) looks more complete, WDYT?

**Comment by josipgrgurica** [comment]
Yes it does. I'll use that one.

**Comment by vil1** [comment]
Fixed by #12
